# Use the latest Ubuntu as base image
FROM ubuntu:latest

# Update package list
RUN apt-get update

# Upgrade installed packages
RUN apt-get upgrade -y

# Set the default command to echo "Hello, World!"
CMD echo "Hello, World!"
